version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
  mongo-seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./initUser.json:/initUser.json
    command: 'mongoimport --host mongodb --db users --collection users --type json --file /initUser.json --jsonArray'
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
  user:
    build:
      context: user
    depends_on:
      - 'mongodb'
      - 'rabbitmq'
    restart: on-failure
    links:
      - rabbitmq
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: topSecret
      MYSQL_ROOT_HOST:%
    ports:
      - 3306:3306
    volumes:
      - ./initMovie.sql:/initMovie.sql
    command: 'mysqld --init-file=/initMovie.sql'
  movie:
    build:
      context: movie
    depends_on:
      - 'mysql'
    restart: on-failure
  api:
    build:
      context: api
    ports:
      - 8080:8080
    depends_on:
      - 'user'
      - 'movie'
    restart: on-failure
    links:
      - rabbitmq
